name: Android NDK Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r25c   # đổi version nếu project cần version khác

      - name: Show NDK path & version
        run: |
          echo "NDK dir: $ANDROID_NDK_HOME"
          $ANDROID_NDK_HOME/ndk-build --version || true

      - name: Build with ndk-build
        working-directory: example-android
        run: |
          ndk-build NDK_PROJECT_PATH=. APP_BUILD_SCRIPT=Android.mk NDK_APPLICATION_MK=Application.mk
