name: Android NDK Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r25c   # đổi version nếu project cần version khác

      - name: Show NDK path & version
        run: |
          echo "NDK dir: $ANDROID_NDK_HOME"
          $ANDROID_NDK_HOME/ndk-build --version || true

      - name: Build with ndk-build
        run: |
          $ANDROID_NDK_HOME/ndk-build \
            APP_BUILD_SCRIPT=example-android/Android.mk \
            NDK_APPLICATION_MK=example-android/Application.mk
