name: Android NDK Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r25c   # hoặc version mà project hỗ trợ

      - name: Build with ndk-build
        working-directory: example-android
        run: ndk-build NDK_PROJECT_PATH=. APP_BUILD_SCRIPT=Android.mk
